#!/bin/bash

# MythSeeker Development Setup Script
# Fetches secrets from Google Secret Manager and creates .env.development

set -e

echo "🔧 Setting up MythSeeker development environment..."

# Check if gcloud is authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | grep -q .; then
    echo "❌ Error: Not authenticated with gcloud. Please run 'gcloud auth login' first."
    exit 1
fi

# Set the project
PROJECT_ID="mythseekers-rpg"
gcloud config set project $PROJECT_ID

# Create .env.development file
ENV_FILE=".env.development"

echo "# MythSeeker Development Environment" > "$ENV_FILE"
echo "# Generated by dev-setup.sh on $(date)" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# Fetch Firebase API Key
echo "📡 Fetching Firebase API Key..."
FIREBASE_API_KEY=$(gcloud secrets versions access latest --secret="firebase-api-key" 2>/dev/null)
if [ -n "$FIREBASE_API_KEY" ]; then
    echo "✅ Firebase API Key fetched successfully"
    echo "VITE_FIREBASE_API_KEY=$FIREBASE_API_KEY" >> "$ENV_FILE"
else
    echo "❌ Failed to fetch Firebase API Key"
    exit 1
fi

# Add other Firebase configuration
echo "VITE_FIREBASE_AUTH_DOMAIN=mythseekers-rpg.firebaseapp.com" >> "$ENV_FILE"
echo "VITE_FIREBASE_PROJECT_ID=mythseekers-rpg" >> "$ENV_FILE"
echo "VITE_FIREBASE_STORAGE_BUCKET=mythseekers-rpg.appspot.com" >> "$ENV_FILE"
echo "VITE_FIREBASE_MESSAGING_SENDER_ID=659018227506" >> "$ENV_FILE"
echo "VITE_FIREBASE_APP_ID=1:659018227506:web:82425e7adaf80c2e3c412b" >> "$ENV_FILE"
echo "VITE_GOOGLE_CLOUD_PROJECT_ID=mythseekers-rpg" >> "$ENV_FILE"
echo "VITE_APP_ENVIRONMENT=development" >> "$ENV_FILE"

# Fetch optional secrets if they exist
echo "📡 Fetching optional secrets..."

# OpenAI API Key
OPENAI_API_KEY=$(gcloud secrets versions access latest --secret="openai-api-key" 2>/dev/null)
if [ -n "$OPENAI_API_KEY" ]; then
    echo "✅ OpenAI API Key fetched successfully"
    echo "VITE_OPENAI_API_KEY=$OPENAI_API_KEY" >> "$ENV_FILE"
else
    echo "⚠️  OpenAI API Key not found (optional)"
fi

# Vertex AI API Key
VERTEX_AI_API_KEY=$(gcloud secrets versions access latest --secret="vertex-ai-api-key" 2>/dev/null)
if [ -n "$VERTEX_AI_API_KEY" ]; then
    echo "✅ Vertex AI API Key fetched successfully"
    echo "VITE_VERTEX_AI_API_KEY=$VERTEX_AI_API_KEY" >> "$ENV_FILE"
else
    echo "⚠️  Vertex AI API Key not found (optional)"
fi

echo ""
echo "✅ Development environment setup complete!"
echo "📁 Created: $ENV_FILE"
echo ""
echo "🚀 You can now run: npm run dev"
echo ""
echo "📋 Environment variables loaded:"
echo "   - Firebase API Key: ✅"
echo "   - Firebase Auth Domain: ✅"
echo "   - Firebase Project ID: ✅"
echo "   - Firebase Storage Bucket: ✅"
echo "   - Firebase Messaging Sender ID: ✅"
echo "   - Firebase App ID: ✅"
echo "   - Google Cloud Project ID: ✅"
echo "   - App Environment: ✅"
if [ -n "$OPENAI_API_KEY" ]; then
    echo "   - OpenAI API Key: ✅"
else
    echo "   - OpenAI API Key: ❌ (not configured)"
fi
if [ -n "$VERTEX_AI_API_KEY" ]; then
    echo "   - Vertex AI API Key: ✅"
else
    echo "   - Vertex AI API Key: ❌ (not configured)"
fi 